sudo: false
language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
  - 5.6
  - hhvm

install:
  # note ignore platform requests below for this: https://github.com/composer/composer/issues/4976
  - composer install --ignore-platform-reqs

script:
- composer run-script test

